# Disabling workspace support
[config]
default_to_workspace = false


[tasks.clean]
description = "clean: remove the target directory"
category = "Build"
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
env = { "SQLX_OFFLINE" = "true" }
args = ["build"]
dependencies = ["clean"]

[tasks.check]
description = "build: analyze the workspace and report errors, but don't build object files"
category = "Build"
env = { "SQLX_OFFLINE" = "true" }
command = "cargo"
args = ["check"]

[tasks.test]
description = "test: run the tests"
category = "Check"
env = { "SQLX_OFFLINE" = "true", "TEST_LOG" = "true", RUSTFLAGS = "-Cinstrument-coverage", LLVM_PROFILE_FILE = "target/%p-%m.profraw" }
command = "cargo"
args = ["test", "--no-fail-fast", "--", "--test-threads", "2"]

[tasks.code-coverage]
description = "llvm-cov: generate HTML coverage report"
category = "Check"
command = "cargo"
install_crate = { rustup_component_name = "llvm-tools-preview", binary = "llvm-profdata", test_arg = "--help" }
env = { "SQLX_OFFLINE" = "true", "TEST_LOG" = "true", RUSTFLAGS = "-Cinstrument-coverage", LLVM_PROFILE_FILE = "target/%p-%m.profraw" }
args = ["llvm-cov", "--html"]

[tasks.tarpaulin]
description = "tarpaulin: compute the code coverage"
category = "Check"
install_crate = "cargo-tarpaulin"
command = "cargo"
args = ["tarpaulin", "--out", "html", "--", "--test-threads", "2"]
disabled = true

[tasks.check-disk-space]
description = "check-disk-space: comprehensive disk space monitoring for host and Podman VM"
category = "System"
script_runner = "bash"
script = "scripts/check-disk-space.sh"
env = { "BASH_SILENCE_DEPRECATION_WARNING" = "1" }

[tasks.debug]
description = "debug: start rc-web in debug mode using mirrord with dynamic pod detection"
category = "Debug"
script_runner = "bash"
script = "scripts/debug-mirrord.sh"
env = { "BASH_SILENCE_DEPRECATION_WARNING" = "1" }

