### Test GET request
GET http://localhost:8080/

### Test POST request Should fail
POST http://localhost:8080/create_def
Content-Type: application/json

{
  "id": "test_id",
  "schema": "test_schema"
}


### Test POST request with valid json
POST http://localhost:8080/create_def
Content-Type: application/json

{
  "title": "test_title_13",
  "type": "object",
  "properties": {
    "example": {
      "type": "string"
    }
  }
}