### Test GET request
GET http://localhost:8080/

### Test POST request Should fail
POST http://localhost:8080/create_def
Content-Type: application/json

{
  "id": "test_id",
  "schema": "test_schema"
}


### Test POST request with valid json
POST http://localhost:8080/create_def
Content-Type: application/json

{
  "title": "test_title_3",
  "type": "object",
  "properties": {
    "example": {
      "type": "string"
    }
  }
}

### Test validation
POST http://localhost:8080/validate_def
Content-Type: application/json

{
  "def_id": "4b736e56-8c99-c1c0-bd55-16175ec63f76"
}


### Test Activation
POST http://localhost:8080/activate_def
Content-Type: application/json

{
  "def_id": "4b736e56-8c99-c1c0-bd55-16175ec63f76"
}

