@host = http://localhost:8000
#@host = https://daksha-ox98.shuttle.app

# Health Check
### Simple hello returns Hello world!
GET {{host}}/hello

### Test GET echo Returns auth failure
POST {{host}}/echo
Content-Type: application/json

{
  "id": "test_id",
  "schema": "test_schema"
}


### Check health returns healthy
GET {{host}}/healthz

### Check readiness returns ready
GET {{host}}/readyz

# Schema apis
### Create schema Should fail
POST {{host}}/api/v1/schema/create_def
Content-Type: application/json

{
  "id": "test_id",
  "schema": "test_schema"
}


### Create schema with valid json test_title_3
POST {{host}}/api/v1/schema/create_def
Content-Type: application/json

{
  "title": "test_title_3",
  "type": "object",
  "properties": {
    "example": {
      "type": "string"
    }
  }
}

### Create schema with valid json test_title_11
POST {{host}}/api/v1/schema/create_def
Content-Type: application/json

{
  "title": "test_title_11",
  "type": "object",
  "properties": {
    "example": {
      "type": "string"
    }
  }
}


### Validate Schema test_title_3
POST {{host}}/api/v1/schema/validate_def
Content-Type: application/json

{
  "id": "4b736e56-8c99-c1c0-bd55-16175ec63f76"
}


### Validate Schema test_title_11
POST {{host}}/api/v1/schema/validate_def
Content-Type: application/json

{
  "id": "87603da8-1778-0450-b5a6-42d26c3adc7e"
}


### Activate Schema test_title_3
POST {{host}}/api/v1/schema/activate_def
Content-Type: application/json

{
  "id": "4b736e56-8c99-c1c0-bd55-16175ec63f76 "
}


### Activate Schema test_title_11
POST {{host}}/api/v1/schema/activate_def
Content-Type: application/json

{
  "id": "87603da8-1778-0450-b5a6-42d26c3adc7e"
}


### Create Schema Student
POST {{host}}/api/v1/schema/create_def
Content-Type: application/json

< ./Student_Schema.json

### Validate Student
POST {{host}}/api/v1/schema/validate_def
Content-Type: application/json

{
  "id": "1bd23c91-3379-b65b-11cc-64984050e35c"
}


### Activate Student
POST {{host}}/api/v1/schema/activate_def
Content-Type: application/json

{
  "id": "1bd23c91-3379-b65b-11cc-64984050e35c"
}


### Hello Entity return Hello world!
GET {{host}}/api/v1/entity/hello

### Create Entity Student
POST {{host}}/api/v1/entity/Student
Content-Type: application/json

{
  "Student": {
    "identityDetails": {
      "fullName": "John",
      "gender": "Male"
    },
    "contactDetails": {
      "email": "abc@abc.com",
      "address": "line1"
    }
  }
}

##### Start of Student1

### Create Schema Student1
POST {{host}}/api/v1/schema/create_def
Content-Type: application/json

< ./Student1_Schema.json

### Validate Student1
POST {{host}}/api/v1/schema/validate_def
Content-Type: application/json

{
  "id": "80c7a337-83b2-9182-dac8-bff24e47cec1"
}


### Activate Student1
POST {{host}}/api/v1/schema/activate_def
Content-Type: application/json

{
  "id": "80c7a337-83b2-9182-dac8-bff24e47cec1"
}


### Hello Entity return Hello world!
GET {{host}}/api/v1/entity/hello

### Create Entity Student1
POST {{host}}/api/v1/entity/Student1
Content-Type: application/json

{
  "Student1": {
    "identityDetails": {
      "fullName": "John1",
      "gender": "Male"
    },
    "contactDetails": {
      "email": "abc@abc.com",
      "address": "line1"
    }
  }
}


#### End of Student1

### Get Definitions by record_status
GET {{host}}/api/v1/schema?record_status=Active

### Get Definitions by titles
GET {{host}}/api/v1/schema?TITLE=Student


### Test POST request Should fail
POST {{host}}/api/v1/schema/create_def
Content-Type: application/json

{
  "id": "test_id",
  "schema": "test_schema"
}

### Get Definitions by id Student
GET {{host}}/api/v1/schema/1bd23c91-3379-b65b-11cc-64984050e35c

### Get Definitions by id test_title_11
GET {{host}}/api/v1/schema/87603da8-1778-0450-b5a6-42d26c3adc7e

### Get Definitions by id test_title_3
GET {{host}}/api/v1/schema/4b736e56-8c99-c1c0-bd55-16175ec63f76

### Get Definitions
GET {{host}}/api/v1/schema

### OpenAPI
GET {{host}}/api-docs/openapi.json

### SwaggerUI
GET {{host}}/swagger-ui/
